# ruby 1.8.7 required trailing dots
Layout/DotPosition:
  EnforcedStyle: trailing

# Over time we'd like to get this down, but this is what we're at now.
Metrics/CyclomaticComplexity:
  Max: 10

# Over time we'd like to get this down, but this is what we're at now.
Metrics/LineLength:
  Max: 186

# Over time we'd like to get this down, but this is what we're at now.
Metrics/MethodLength:
  Max: 50

# each_with_object was unavailable on ruby 1.8.7
Style/EachWithObject:
  Enabled: false

# ruby 1.8.7 only had support for hash rockets
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# the new lambda syntax was not supported in ruby 1.8.7
Style/Lambda:
  Enabled: false
