inherit_from:
  - .rubocop_todo.yml
  - .rubocop_rspec_base.yml

# We use spaces, so it's less of a change to stick with that.
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

################################################################################
# Individual File Exclusions
################################################################################

AllCops:
  Exclude:
    # Templates are really ERB which Rubocop does not parse
    - 'lib/generators/rspec/*/templates/**/*'

Naming/FileName:
  Exclude:
    # We break convention here so that when bundler requires the gem, which
    # uses the gem name, things work without user configuration.
    - lib/rspec-rails.rb

Lint/SuppressedException:
  Exclude:
    # RSpec is tightly coupled to capybara right now, this should be
    # re-evaluted in the future. For now we allow the empty rescue
    - lib/rspec/rails/vendor/capybara.rb

Style/IfUnlessModifier:
  Exclude:
    # Allow single line statement as the style matches the remainder of the file
    - lib/rspec/rails/vendor/capybara.rb

Style/PerlBackrefs:
  Exclude:
    # We probably can refactor the backref out, but for now excluding it since
    # we can't use named matches in 1.8.7
    - lib/generators/rspec/scaffold/scaffold_generator.rb

Style/AccessModifierDeclarations:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/EmptyExpression:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
