language: ruby

rvm:
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7

env:
  - RAILS_VERSION=master
  - RAILS_VERSION='~> 4.1.0'
  - RAILS_VERSION=4-1-stable
  - RAILS_VERSION='~> 4.0.4'
  - RAILS_VERSION=4-0-stable
  - RAILS_VERSION='~> 3.2.17'
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION='~> 3.1.12'
  - RAILS_VERSION='~> 3.0.20'

sudo: false

bundler_args: "--binstubs --path ../bundle --retry=3 --jobs=3"

before_install:
  # Downgrade bundler to work around https://github.com/bundler/bundler/issues/3004
  - gem install bundler -v=1.5.3
  - alias bundle="bundle _1.5.3_"

before_script:
  # Rails 4.x complains with a bundler rails binstub in PROJECT_ROOT/bin/
  - rm -f bin/rails
  - bundle exec rails --version

script: "script/run_build 2>&1"

matrix:
  exclude:
    # 3.0.x is not supported on MRI 2.0+
    - rvm: 2.0.0
      env: RAILS_VERSION='~> 3.0.20'
    - rvm: 2.1.0
      env: RAILS_VERSION='~> 3.0.20'
    - rvm: 2.1.1
      env: RAILS_VERSION='~> 3.0.20'
    - rvm: 2.1.2
      env: RAILS_VERSION='~> 3.0.20'
    # 4.0.x is not supported on MRI ruby-1.8.7 or 1.9.2
    - rvm: 1.8.7
      env: RAILS_VERSION='~> 4.0.4'
    - rvm: 1.9.2
      env: RAILS_VERSION='~> 4.0.4'
    - rvm: 1.8.7
      env: RAILS_VERSION=4-0-stable
    - rvm: 1.9.2
      env: RAILS_VERSION=4-0-stable
    # 4.1.x is not supported on MRI ruby-1.8.7 or 1.9.2
    - rvm: 1.8.7
      env: RAILS_VERSION='~> 4.1.0'
    - rvm: 1.9.2
      env: RAILS_VERSION='~> 4.1.0'
    - rvm: 1.8.7
      env: RAILS_VERSION=4-1-stable
    - rvm: 1.9.2
      env: RAILS_VERSION=4-1-stable
    # master is not supported on MRI ruby-1.8.7 or 1.9.2
    - rvm: 1.8.7
      env: RAILS_VERSION=master
    - rvm: 1.9.2
      env: RAILS_VERSION=master
  allow_failures:
    - env: RAILS_VERSION=master
